Repository Arlissonjaques/capim-code, pull requests merged in 2024-03, with the labels that each got.

#21 adjust logo responsiveness
  assets/css/main.css
Labels: style

#22 Change logo color and mobile menu
  assets/css/main.css
  assets/css/variables.css
Labels: style

#30 smooth scroll fix
  index.html
Labels: feat

#31 commented on the brands section
  index.html
Labels: content

#29 adjustment of the contact form
  assets/css/main.css
Labels: style
